<?php
/**
 * @file
 * Code for the Catman commerece feature.
 */

include_once 'catman_commerce.features.inc';

/**
 * Implements hook_commerce_order_state_info_alter().
 *
 * Add returns state.
 */
function catman_commerce_commerce_order_state_info_alter(&$order_states)  {
  $order_states['returns'] = array(
    'name' => 'returns',
    'title' => t('Returns'),
    'description' => t('Orders in this state have been are in the process of being returned or refunded'),
    'weight' => 9,
    'default_status' => 'return_received',
    );

  return $order_states;
}


/**
 * Implements hook_commerce_order_status_info().
 *
 * Add statuses to the pending and return to order states.
 */
function catman_commerce_commerce_order_status_info() {

  $order_statuses['ready_for_pickup'] = array(
    'name' => 'ready_for_pickup',
    'title' => t('Ready for pickup'),
    'state' => 'pending',
    'weight' => '10',
  );

  $order_statuses['paid_pod'] = array(
    'name' => 'paid_pod',
    'title' => t('Paid - POD'),
    'state' => 'pending',
    'weight' => '11',
  );

  $order_statuses['unpaid_pod'] = array(
    'name' => 'unpaid_pod',
    'title' => t('Unpaid - POD'),
    'state' => 'pending',
    'weight' => '12',
  );

  $order_statuses['shipped_paid'] = array(
    'name' => 'shipped_paid',
    'title' => t('Shipped and paid'),
    'state' => 'pending',
    'weight' => '13',
  );

  $order_statuses['shipped_unpaid'] = array(
    'name' => 'shipped_unpaid',
    'title' => t('Shipped and unpaid'),
    'state' => 'pending',
    'weight' => '14',
  );

  $order_statuses['return_received'] = array(
    'name' => 'return_received',
    'title' => t('Return received'),
    'state' => 'returns',
    'weight' => '15',
  );

  $order_statuses['refund_processing'] = array(
    'name' => 'refund_processing',
    'title' => t('Refund processing'),
    'state' => 'returns',
    'weight' => '16',
  );

  $order_statuses['refunded'] = array(
    'name' => 'refunded',
    'title' => t('Refunded'),
    'state' => 'returns',
    'weight' => '17',
  );

  return $order_statuses;
}


/*
  * Creates an option for custom callback on commerce_invoice settings page
  *
  */
function catman_commerce_catman_invoice_number_callbacks() {
  return array('catman_commerce_invoice_gen' => t('Catman invoice number'));
}

/*
 * Callback for generating a custom invoice number
 * Sets the invoice number by concatenating the date('Y-m') with the order_id
 *
 */
function catman_commerce_invoice_gen($invoice = NULL) {
  $order_id = $invoice->order_id;
  $invoice_prefix = date('Y-m') . '-';
  return $invoice_prefix . $order_id;
}


/**
 * Implements hook_form_alter().
 */
function catman_commerce_form_alter(&$form, &$form_state, $form_id) {
  // Don't show country drop-down list on checkout form
  if ($form_id == 'commerce_checkout_form_checkout') {
    // dpm($form, 'form array');
    $form['customer_profile_billing']['commerce_customer_address']['und'][0]['country']['#access'] = FALSE;
    $form['customer_profile_shipping']['commerce_customer_address']['und'][0]['country']['#access'] = FALSE;
  }

}


/**
 * Implements hook_commerce_price_formatted_components_alter().
 */
function catman_commerce_commerce_price_formatted_components_alter(&$components, $price, $entity) {
  // We modify $variables to "merge" base_price and discount
  if ( isset($components['base_price']) && !empty($components['base_price']) &&
    isset($components['discount']) && !empty($components['discount'])) {
    // We calculate the new price with included discount
    $price_with_discount_amount = $components['base_price']['price']['amount'] + $components['discount']['price']['amount'];
    // We format this price with the used currency
    $price_with_discount_formatted = commerce_currency_format($price_with_discount_amount, $components['base_price']['price']['currency_code']);
    // We update the display of base_price component with the new price
    $components['base_price']['price']['amount'] = $price_with_discount_amount;
    $components['base_price']['formatted_price'] = $price_with_discount_formatted;
    // We unset the display of discount
    unset($components['discount']);
  }
}


