<?php
/**
 * @file
 * Code for the Catman commerece feature.
 */

include_once 'catman_commerce.features.inc';

/**
 * Implements hook_commerce_order_state_info_alter().
 *
 * Add returns state.
 */
function catman_commerce_commerce_order_state_info_alter(&$order_states)  {
  $order_states['returns'] = array(
    'name' => 'returns',
    'title' => t('Returns'),
    'description' => t('Orders in this state have been are in the process of being returned or refunded'),
    'weight' => 9,
    'default_status' => 'return_received',
    );

  return $order_states;
}


/**
 * Implements hook_commerce_order_status_info().
 *
 * Add statuses to the pending and return to order states.
 */
function catman_commerce_commerce_order_status_info() {

  $order_statuses['ready_for_pickup'] = array(
    'name' => 'ready_for_pickup',
    'title' => t('Ready for pickup'),
    'state' => 'pending',
    'weight' => '10',
  );

  $order_statuses['shipped_paid'] = array(
    'name' => 'shipped_paid',
    'title' => t('Shipped and paid'),
    'state' => 'pending',
    'weight' => '11',
  );

  $order_statuses['shipped_unpaid'] = array(
    'name' => 'shipped_unpaid',
    'title' => t('Shipped and unpaid'),
    'state' => 'pending',
    'weight' => '12',
  );

  $order_statuses['return_received'] = array(
    'name' => 'return_received',
    'title' => t('Return received'),
    'state' => 'returns',
    'weight' => '15',
  );

  $order_statuses['refunded'] = array(
    'name' => 'refunded',
    'title' => t('Refunded'),
    'state' => 'returns',
    'weight' => '16',
  );



  // remove processing status (we may want to add this back at some point)
  // $order_statuses['processing'] = array(
  //   'state' => 'pending',
  //   'status' => FALSE,
  // );

  return $order_statuses;
}

/*
  * Creates an option for custom callback on commercie_invoice settings page
  *
  */
function catman_commerce_catman_invoice_number_callbacks() {
  return array('catman_commerce_invoice_gen' => t('Catman invoice number'));
}

/*
 * Callback for generating a custom invoice number
 * Sets the invoice number by concatenating the date('Y-m') with the order_id
 *
 */
function catman_commerce_invoice_gen($invoice = NULL) {
  $order_id = $invoice->order_id;
  $invoice_prefix = date('Y-m') . '-';
  return $invoice_prefix . $order_id;
}






